version: 0.1.{build}

branches:
  only:
  - master

clone_depth: 20

before_build:
- cmd: nuget restore

build:
  project: Seq.Slack.csproj
  verbosity: minimal
 
after_build:
- cmd: nuget pack Seq.Slack.csproj -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
- path: '*.nupkg'
  name: nuget-package
  
deploy:
- provider: NuGet
  api_key:
    secure: N2N9XYHL6Cw56Q/wkqHfbeWmTd3aDlDbLj6csA/Ws5gdq4GZDyZ3UK5z7+Hb0gD8
  artifact: nuget-package
  on:
    branch: master
