version: 0.2.{build}
image: Visual Studio 2017

branches:
  only:
  - master

clone_depth: 20

before_build:
- cmd: nuget restore

build:
  project: src\Seq.App.Slack\Seq.App.Slack.csproj
  verbosity: minimal
 
after_build:
- cmd: nuget pack src\Seq.App.Slack\Seq.App.Slack.csproj -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
- path: 'Seq.App.Slack.*.nupkg'
  name: nuget-package
  
deploy:
- provider: NuGet
  api_key:
    secure: N2N9XYHL6Cw56Q/wkqHfbeWmTd3aDlDbLj6csA/Ws5gdq4GZDyZ3UK5z7+Hb0gD8
  artifact: nuget-package
  on:
    branch: master
